<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>
	
  <ItemGroup>
    <ProjectReference Include="..\FileMaterialization\FileMaterialization.csproj" />
    <ProjectReference Include="..\UnrealMaterialization\UnrealMaterialization.csproj" />
    <ProjectReference Include="..\SystemUtilities\SystemUtilities.csproj" />
    <ProjectReference Include="..\UnrealPluginFlattening\UnrealPluginFlattening\UnrealPluginFlattening.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.Common" Version="3.11.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Semver" Version="2.3.0" />
  </ItemGroup>

	<ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="templates\*.template">
      <WithCulture>false</WithCulture>
      <LogicalName>UnrealUtilities.templates.%(Filename)%(Extension)</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>
