<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SystemUtilities\SystemUtilities.csproj" />
    <ProjectReference Include="..\LocalAutomation.Core\LocalAutomation.Core.csproj" />
    <ProjectReference Include="..\LocalAutomation.Runtime\LocalAutomation.Runtime.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.2.2" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.5" />
  </ItemGroup>

</Project>
